version: '3.8'

services : 
  backend :
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"    #Host:5000 → Container:5000
    volumes:
      - ./backend:/app
      - todo_data:/app/data
    environment:
      - FLASK_ENV=development
      #- FLASK_APP=app.py
      - PORT=5000   # Matches internal port
    healthcheck:
      test : ["CMD", "curl", "-f", "http://backend:5000/health"] # Test internal port 
      interval : 30s
      timeout : 10s
      retries: 3
    networks :
      - todo-network
  
  frontend :
    build:
      context : ./frontend
      dockerfile: Dockerfile
    ports :
     - "3000:3000"  # Host:3000 → Nginx:3000    
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    depends_on:
      - backend
    networks :
     - todo-network

  # Database (Optional: PostgreSQL for production)
  # Uncomment if you want to use PostgreSQL instead of SQLite
  # database:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: todoapp
  #     POSTGRES_USER: todouser
  #     POSTGRES_PASSWORD: todopass
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - todo-network

volumes: # Declaration of names volumes  
    todo_data:
    # postgres_data:

networks:
  todo-network:
    driver: bridge
  




